server:
  port: 9005
spring:
  application:
    name: DiscoveryService
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    serviceUrl:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka